---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: secondarynet
spec:
  config: '{
      "cniVersion": "0.3.0",
      "name": "ovnnet1",
      "type": "ovn-cni",
      "subnet": "123.123.123.0/24"
    }'
---
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: secondarynet2
spec:
  config: '{
      "cniVersion": "0.3.0",
      "name": "ovnnet2",
      "type": "ovn-cni",
      "subnet": "200.200.200.0/24"
    }'
---
apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    k8s.v1.cni.cncf.io/networks: secondarynet
spec:
  containers:
  - name: samplepod
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: dougbtv/centos-network
---
apiVersion: v1
kind: Pod
metadata:
  name: samplepod2
  annotations:
    k8s.v1.cni.cncf.io/networks: secondarynet2
spec:
  containers:
  - name: samplepod2
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: dougbtv/centos-network
---
apiVersion: v1
kind: Pod
metadata:
  name: samplepod3
  annotations:
    k8s.v1.cni.cncf.io/networks: secondarynet2
spec:
  containers:
  - name: samplepod3
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: dougbtv/centos-network
